# Generated by Django 5.1.7 on 2025-04-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="blog_id",
            new_name="blog",
        ),
    ]
